baseURL: "https://nicolas-astorga.github.io/"
title: "Nicolás Astorga"
paginate: 10
enableRobotsTXT: true
outputs:
  home: ["HTML", "JSON"]
module:
  hugoVersion:
    extended: true
    min: "0.128.2"
minify:
  disableXML: true
disableKinds:
  - RSS
