# Site-wide params for Hugo Blox / Wowchemy
site_type: Person

# Appearance
appearance:
  theme_day: minimal
  theme_night: minimal
  font: minimal
  font_size: m

footer:
  copyright:
    notice: "© 2025 Nicolas Astorga"
  show_translations: false

# Enable search if you want it
features:
  search:
    provider: fuse
    enable: true

# Enable Academicons icon set for Google Scholar, arXiv, ORCID, etc.
extensions:
  academicons:
    enable: true

# Map provider (optional for contact map)
map:
  provider: "osm"

# SEO
seo:
  site_description: "PhD researcher at the University of Cambridge (van der Schaar Lab). Reasoning with LLMs, Bayesian experimental design, and optimization."

# Menu settings (header)
main_menu:
  align: right
  show_logo: false
  show_theme_chooser: true
  show_language: false
  show_search: true
